import type {
  EditorShortcut,
  EditorShortcutGroup,
} from "../types/editor-shortcut.types";

export const editorShortcutGroups: readonly EditorShortcutGroup[] = [
  {
    id: "general",
    label: "General",
  },
  {
    id: "formatting",
    label: "Formatting",
  },
  {
    id: "blocks",
    label: "Blocks",
  },
  {
    id: "history",
    label: "History",
  },
  {
    id: "media",
    label: "Media and commands",
  },
];

export const editorShortcuts: readonly EditorShortcut[] = [
  {
    id: "open-shortcuts",
    groupId: "general",
    label: "Open keyboard shortcuts",
    description: "View and search the editor shortcut reference.",
    keywords: ["help", "keyboard", "reference", "shortcuts"],
    macKeys: ["⌘", "/"],
    windowsKeys: ["Ctrl", "/"],
  },
  {
    id: "select-all",
    groupId: "general",
    label: "Select all",
    description: "Select all content in the current editor.",
    keywords: ["selection", "document", "all"],
    macKeys: ["⌘", "A"],
    windowsKeys: ["Ctrl", "A"],
  },
  {
    id: "bold",
    groupId: "formatting",
    label: "Bold",
    description: "Toggle bold formatting for the current selection.",
    keywords: ["strong", "weight", "format"],
    macKeys: ["⌘", "B"],
    windowsKeys: ["Ctrl", "B"],
  },
  {
    id: "italic",
    groupId: "formatting",
    label: "Italic",
    description: "Toggle italic formatting for the current selection.",
    keywords: ["emphasis", "format"],
    macKeys: ["⌘", "I"],
    windowsKeys: ["Ctrl", "I"],
  },
  {
    id: "strike",
    groupId: "formatting",
    label: "Strikethrough",
    description: "Toggle strikethrough formatting.",
    keywords: ["strike", "deleted", "format"],
    macKeys: ["⌘", "Shift", "S"],
    windowsKeys: ["Ctrl", "Shift", "S"],
  },
  {
    id: "inline-code",
    groupId: "formatting",
    label: "Inline code",
    description: "Format selected text as inline code.",
    keywords: ["developer", "code", "monospace"],
    macKeys: ["⌘", "E"],
    windowsKeys: ["Ctrl", "E"],
  },
  {
    id: "paragraph",
    groupId: "blocks",
    label: "Paragraph",
    description: "Convert the current block to normal text.",
    keywords: ["plain", "text", "normal"],
    macKeys: ["⌘", "⌥", "0"],
    windowsKeys: ["Ctrl", "Alt", "0"],
  },
  {
    id: "heading-1",
    groupId: "blocks",
    label: "Heading 1",
    description: "Convert the current block to Heading 1.",
    keywords: ["title", "heading", "h1"],
    macKeys: ["⌘", "⌥", "1"],
    windowsKeys: ["Ctrl", "Alt", "1"],
  },
  {
    id: "heading-2",
    groupId: "blocks",
    label: "Heading 2",
    description: "Convert the current block to Heading 2.",
    keywords: ["subtitle", "heading", "h2"],
    macKeys: ["⌘", "⌥", "2"],
    windowsKeys: ["Ctrl", "Alt", "2"],
  },
  {
    id: "heading-3",
    groupId: "blocks",
    label: "Heading 3",
    description: "Convert the current block to Heading 3.",
    keywords: ["heading", "h3"],
    macKeys: ["⌘", "⌥", "3"],
    windowsKeys: ["Ctrl", "Alt", "3"],
  },
  {
    id: "bullet-list",
    groupId: "blocks",
    label: "Bullet list",
    description: "Toggle an unordered list.",
    keywords: ["bullet", "unordered", "list"],
    macKeys: ["⌘", "Shift", "8"],
    windowsKeys: ["Ctrl", "Shift", "8"],
  },
  {
    id: "ordered-list",
    groupId: "blocks",
    label: "Numbered list",
    description: "Toggle an ordered list.",
    keywords: ["ordered", "number", "list"],
    macKeys: ["⌘", "Shift", "7"],
    windowsKeys: ["Ctrl", "Shift", "7"],
  },
  {
    id: "undo",
    groupId: "history",
    label: "Undo",
    description: "Undo the most recent editor change.",
    keywords: ["history", "previous", "revert"],
    macKeys: ["⌘", "Z"],
    windowsKeys: ["Ctrl", "Z"],
  },
  {
    id: "redo",
    groupId: "history",
    label: "Redo",
    description: "Restore the most recently undone change.",
    keywords: ["history", "restore", "repeat"],
    macKeys: ["⌘", "Shift", "Z"],
    windowsKeys: ["Ctrl", "Shift", "Z"],
  },
  {
    id: "slash-command",
    groupId: "media",
    label: "Open slash commands",
    description: "Search blocks and insertion commands inside the editor.",
    keywords: ["menu", "blocks", "insert", "commands"],
    macKeys: ["/"],
    windowsKeys: ["/"],
  },
];
